Paymentauthorization/Models/Province.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paymentauthorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public int id { get; set; }
        public string ProvincesNAme { get; set; }
    }
}

Paymentauthorization/Controllers/provincesController.cs
using Paymentauthorization.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Paymentauthorization.Controllers
{
    public class provincesController : Controller
    {
        Admin_DBEntities db = new Admin_DBEntities();
        // GET: provinces
        public ActionResult Index()
        {
            return View(db.Provinces.ToList());
        }

        [HttpPost]
        public ActionResult Index(Province province)
        {
            db.Provinces.Add(province);
            db.SaveChanges();

            return View(db.Provinces.ToList());
        }
        // GET: provinces/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: provinces/Create
        public ActionResult Create()
        {
            Admin_DBEntities db = new Admin_DBEntities();
            var pro=db.Provinces.ToList();
            
            return View();
        }

        // POST: provinces/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: provinces/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: provinces/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: provinces/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: provinces/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Paymentauthorization/Views/provinces/Create.cshtml
@model Paymentauthorization.Models.User

@{
    ViewBag.Title = "qw";
}

<h2>qw</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserNAme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserNAme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserNAme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person_phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person_phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person_phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Person_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Person_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Person_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Paymentauthorization/Views/provinces/Index.cshtml
@model IEnumerable<Paymentauthorization.Models.Province>

@using (Html.BeginForm("Index", "provinces", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="card">
        <div class="card-header">
            <div class="row justify-content-between">
                <h4 class="col-auto">المحافظات </h4>
            </div>
        </div>
    </div>
    <div class="mb-3">
        <label for="username" class="form-label"> إسم المحافظة : </label>
        <input type="text" class="form-control" id="ProvincesNAme" name="ProvincesNAme" placeholder="المحافظة" required>
        <div class="invalid-feedback">
            أدخل اسم المحافظة
        </div>
    </div>



    <div class="mb-3" style="direction:ltr">
        <button class="btn btn-primary w-34 waves-effect waves-light" type="submit">تسجيل </button>
    </div>
}
<table class="table table-hover">
    <thead class="thead-dark ">
        <tr>
            <th>
                الاسم
            </th>
            <th style="margin-left:100px">
                عمليات
            </th>
        </tr>
    </thead>
    <br>
    <br>
    <hr>
    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProvincesNAme)
            </td>
            <td>
                @Html.ActionLink("تعديل", "Edit", new { id = item.id }) |
                @Html.ActionLink("عرض البيانات  ", "Details", new { id = item.id }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>