Paymentauthorization/Models/City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paymentauthorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int ID { get; set; }
        public Nullable<int> provinceid { get; set; }
        public string CityName { get; set; }
    }
}

Paymentauthorization/Controllers/CitiesController.cs
using Paymentauthorization.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Paymentauthorization.Controllers
{
    public class CitiesController : Controller
    {
        Admin_DBEntities db = new Admin_DBEntities();

        // GET: Cities
        public ActionResult Index()
        {
            var Combo_Provinces = db.Provinces.ToList();

            if (Combo_Provinces != null)
            {
                @ViewBag.data = Combo_Provinces;
            }

            return View(db.Cities.ToList());
        }
        [HttpPost]
        public ActionResult Index(City city)
        {
            db.Cities.Add(city);
            db.SaveChanges();
            return View(db.Cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cities/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cities/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Paymentauthorization/Views/Cities/Index.cshtml
@model IEnumerable<Paymentauthorization.Models.City>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Index", "Cities", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="card">
        <div class="card-header">
            <div class="row justify-content-between">
                <h4 class="col-auto">المدن </h4>
            </div>
        </div>
    </div>
    <div class="col-12">
            <div class="Row">
                <div class="form-group mb-3 col-sm-12">
                    @Html.Label("المحافظة", htmlAttributes: new { @class = "control-label" })
                    <div class="col-12">
                        @Html.DropDownList("id", new SelectList(ViewBag.data, "id", "ProvincesNAme"), "--اختر--", new { @class = "form-control text-center", required = "required" })
                        @Html.ValidationMessage("id", "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    <br>
    <div class="mb-3">
        <label for="username" class="form-label"> إسم المدينة  : </label>
        <input type="text" class="form-control" id="CityName" name="CityName" placeholder="المدينة" required>
        <div class="invalid-feedback">
            أدخل اسم المدينة
        </div>
    </div>



    <div class="mb-3" style="direction:ltr" >
        <button class="btn btn-primary w-35 waves-effect waves-light" type="submit" >تسجيل </button>
    </div>
}
<table class="table table-hover">
    <thead class="thead-dark ">
        <tr>
            <th>
                المحافظة
            </th>   
            <th>
                المدينة
            </th>
            <th style="margin-left:100px">
                عمليات
            </th>
        </tr>
    </thead>
    <br>
  
    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.provinceid)
            </td> 
            <td>
                @Html.DisplayFor(modelItem => item.CityName)
            </td>
            <td>
                @Html.ActionLink("تعديل", "Edit", new { id = item.ID }) |
                @Html.ActionLink("عرض البيانات  ", "Details", new { id = item.ID }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>